name: offline_secure_session
description: Enterprise-grade Dart library for secure token storage with AES-256 encryption, offline action queue, auto-sync on reconnection, and persistent cache.
version: 2.0.0
homepage: https://github.com/jafcn09/offline_secure_session
repository: https://github.com/jafcn09/offline_secure_session
issue_tracker: https://github.com/jafcn09/offline_secure_session/issues

topics:
  - offline
  - session
  - cache
  - queue
  - security

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  crypto: ^3.0.3
  encrypt: ^5.0.3

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0